"""
Script to plot spectra generated by ProSAIL and saved in LUT.
Will show spectra per range of trat (default is LAI)
"""

import os
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np


lut_path = '../results/prosail_danner-etal_switzerland_soil_hyspex_lai-cab-ccc-car_lut.pkl'
trait = 'lai'

df = pd.read_pickle(lut_path)

cols_traits = ['n', 'cab', 'car', 'ant', 'cbrown', 'cw', 'cm', 'prot', 'cbc', 'lai', 'lidfa',\
    'hspot', 'rsoil', 'psoil', 'tts', 'tto', 'psi', 'lidfb', 'typelidf', 'ccc']
cols_bands = [c for c in df.columns if c.startswith('B')]
wvl = pd.read_csv('../data/mjolnir_wvl_fwhm.csv', sep=';')['wvl'].tolist()



fig, axs = plt.subplots(nrows=7, ncols=2, figsize=(14, 20))

min_val, max_val = np.floor(df[trait].min()), np.ceil(df[trait].max())
thresholds = np.linspace(min_val, max_val, 8)

for i in range(len(thresholds) - 1):
    lower, upper = thresholds[i], thresholds[i + 1]
    df_tr = df[(df[trait] >= lower) & (df[trait] < upper)]
    
    sample = df_tr.sample(30, replace=True)

    # Plot individual sampled spectra
    axs[i, 0].plot(wvl, sample[cols_bands].T, linestyle='-')
    axs[i, 0].set_title(f'S2 spectra for {trait} {lower:.5f}-{upper:.5f}')
    axs[i, 0].set_xlabel('Wavelength (nm)')
    axs[i, 0].set_ylabel('Reflectance')
    axs[i, 0].set_ylim(0, 1)  
    axs[i, 0].set_xlim(400, 2300)

    # Plot mean spectrum
    mean_spectrum = df_tr[cols_bands].mean()
    axs[i, 1].plot(wvl, mean_spectrum, color='black', linewidth=2)
    axs[i, 1].set_title(f'Mean spectrum for {trait} {lower:.5f}-{upper:.5f}')
    axs[i, 1].set_xlabel('Wavelength (nm)')
    axs[i, 1].set_ylabel('Reflectance')
    axs[i, 1].set_ylim(0, 1)  
    axs[i, 1].set_xlim(400, 2300)

    plt.tight_layout()
    plt.savefig(f'Hyspex_spectra_{trait}.png')